name = "functx"
version = "1.0.0"
description = "Tiny Gleam caching Context for your functions"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "functx" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
